import type { Metadata } from "next";
import LocalFont from "next/font/local";
import "./globals.css";
import StyledComponentsRegistry from "./lib/registry";
import path from "path";
import Providers from "./providers";

const inter = LocalFont({
  src: [
    {
      path: "../../public/font/inglobal.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/inglobalb.ttf",
      weight: "bold",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Providers>{children} </Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
